

  # 数据源
  spring:
    redis:
      password:
      host: 127.0.0.1
      port: 6379
    datasource:
#      dynamic:
#        primary: master #设置默认的数据源或者数据源组,默认值即为master
#        strict: false #严格匹配数据源,默认false. true未匹配到指定数据源时抛异常,false使用默认数据源
#        datasource:
      master:
        url: jdbc:mysql://127.0.0.1:3306/rx_manager?characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowMultiQueries=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver # 3.2.0开始支持SPI可省略此配置
      slave:
        url: jdbc:mysql://127.0.0.1:3306/booksys?characterEncoding=utf8
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

  logging:
    level:
      com:
        eddy:
          scheme: debug
