# 加解密根密码xxxxxx
jasypt:
  encryptor:
    password: pig #根密码

# spring security 配置
#security:
#  encode:
#    # 前端密码密钥，必须16位
#    key: 'thanks,pig4cloud'
#  client:
#    client-id: ENC(imENTO7M8bLO38LFSIxnzw==)
#    client-secret: ENC(i3cDFhs26sa2Ucrfz2hnQw==)
#    scope: server



# 数据源
spring:
  application:
    name: RxManager
  profiles:
    active: dev
  main:
    allow-bean-definition-overriding: true
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
  messages:
    basename: i18n/message_common
    encoding: UTF-8

  #设置超时时间半小时
#  web:
#    resources:
#      static-locations: classpath:/static/,file:/Users/Eddy/images/
  mvc:
    async:
      request-timeout: 1800000
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    user:
      name: admin
      password: 123456


# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: auto
      table-underline: true
      logic-delete-field: delFlag
      logic-delete-value: 1
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  #开启sql日志


# 直接放行URL
ignore:
  urls:
    - /user/info/*
    - /**
    - /scenario/deploy/*
    - /rxm/hello!